api/urls.py
from django.conf.urls import url

from api import views as api_views

urlpatterns = [
    url(r'^get_captcha/$', api_views.get_captcha.as_view(), name='get_captcha'),
    url(r'^edit_options/$', api_views.edit_options.as_view(), name="edit_options"),
    url(r'^edit_web/$', api_views.edit_web.as_view(), name="edit_web"),
    url(r'^del_web/$', api_views.del_web.as_view(), name="del_web"),
    url(r'^auth/$', api_views.auth.as_view(), name="auth"),
]

django_sso_server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from cas import views as cas_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^start/$', cas_views.start.as_view(), name="start"),
    url(r'^login/$|^$', cas_views.login.as_view(), name="login"),
    url(r'^dashboard/$', cas_views.dashboard.as_view(), name="dashboard"),
    url(r'^manage/$', cas_views.manage.as_view(), name="manage"),
    url(r'^wxconf/$', cas_views.wxconf.as_view(), name="wxconf"),
    url(r'^wxlogin$', cas_views.wxlogin.as_view(), name="wxlogin"),
    url(r'^changepass/', cas_views.change_pass.as_view(), name="changepass"),
    url(r'^logout/', cas_views.logout.as_view(), name="logout"),
    url(r'^api/', include('api.urls', namespace='api')),
    
]

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <!--网页标题左侧显示-->
    <link rel="icon" href="{% static 'image/favicon.ico' %}" type="image/x-icon">
    <!--收藏夹显示图标-->
    <link rel="shortcut icon" href="{% static 'image/favicon.ico' %}" type="image/x-icon">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{% static 'AdminLTE-2.4.5/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'AdminLTE-2.4.5/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'AdminLTE-2.4.5/bower_components/Ionicons/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'AdminLTE-2.4.5/dist/css/AdminLTE.min.css' %}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{% static 'AdminLTE-2.4.5/dist/css/skins/_all-skins.min.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="../../dist/js/html5shiv.min.js"></script>
  <script src="../../dist/js/respond.min.js"></script>
  <![endif]-->
    {% block header_css %}{% endblock %}
</head>
<!-- ADD THE CLASS layout-top-nav TO REMOVE THE SIDEBAR. -->

<body class="hold-transition skin-green layout-top-nav">
    <div class="wrapper">

        <header class="main-header">
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <a href="/" class="navbar-brand"><b>Django sso</b> server</a>
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    {% if admin_flag %}
                    <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                        {% block collapse %}
                        <ul class="nav navbar-nav">
                            <li id="user_page" class="active"><a href="/dashboard/">用户页面</a></li>
                            <li id="back_page" class="menuItem dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true"  role="button" aria-haspopup="true">后台页面 <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li id="manage_page"><a href="/manage/">配置管理后台</a></li>
                                    <li id="wx_conf_page"><a href="/wxconf/">企业微信扫码</a></li>
                                </ul>
                            </li>
                        </ul>
                        {% endblock %}
                    </div>
                    {% endif %}

                    <!-- Navbar Right Menu -->
                    {% if displayName %}
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- User Account Menu -->
                            <li class="dropdown user user-menu">
                                <!-- Menu Toggle Button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <!-- The user image in the navbar-->
                                    <img src="{% static 'AdminLTE-2.4.5/dist/img/user2-160x160.jpg' %}" class="user-image"
                                        alt="User Image">
                                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                    <span class="hidden-xs">{{ displayName }}</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- User image -->
                                    <li class="user-header">
                                        <img src="{% static 'AdminLTE-2.4.5/dist/img/user2-160x160.jpg' %}" class="img-circle"
                                            alt="User Image">
                                        <p>
                                            {{ displayName }}
                                            <small>欢迎你的登陆</small>
                                        </p>
                                    </li>
                                    <!-- Menu Body -->
                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="#" onclick="change_pass()" class="btn btn-default btn-flat">修改密码</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="/logout/" class="btn btn-default btn-flat">注销</a>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </nav>
        </header>
        <!-- Full Width Column -->
        <div class="content-wrapper">
            <div class="container">
                <!-- Content Header (Page header) -->
                <section class="content-header">
                    {% block content_header %}
                    <h1>
                        顶部导航
                        <small>Example 2.0</small>
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
                        <li><a href="#">Layout</a></li>
                        <li class="active">Top Navigation</li>
                    </ol>
                    {% endblock %}
                </section>

                <!-- Main content -->
                <section class="content">
                    {% block content %}
                    <div class="box box-default">
                        <div class="box-header with-border">
                            <h3 class="box-title">Blank Box</h3>
                        </div>
                        <div class="box-body">
                            The great content goes here
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                    {% endblock %}
                    <!-- 编辑添加webs模态框 -->
                    <div class="modal fade modal-default" id="changepass_modal" tabindex="-1" role="dialog"
                        aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="myModalLabel">修改密码</h4>
                                </div>
                                <div class="modal-body">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                        </div>
                                        <div class="panel-body">
                                            <input type="hidden" id="web_id" />
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">原密码</label>
                                                <input class="form-control" id="oldpass" type="password" value="" />
                                            </div>
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">新密码</label>
                                                <input class="form-control" id="newpass1" type="password" value="" />
                                            </div>
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">重复新密码</label>
                                                <input class="form-control" id="newpass2" type="password" value="" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                                    <button type="button" class="btn btn-primary" onclick="submit_changepass()">提交</button>
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal -->
                    </div>
                </section>
                <!-- /.content -->
            </div>
            <!-- /.container -->
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="container">
                <div class="pull-right hidden-xs">
                    <b>^_^ Django sso server</b> v0.0.1
                </div>
                <strong>Copyright &copy; 2018 <a href="http://www.calmkart.com">cAlmkArt</a>.</strong> All rights
                reserved.
            </div>
            <!-- /.container -->
        </footer>
    </div>
    <!-- ./wrapper -->

    <!-- jQuery 2.2.3 -->
    <script src="{% static 'AdminLTE-2.4.5/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.2.0 -->
    <script src="{% static 'AdminLTE-2.4.5/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootbox.min.js' %}"></script>
    {% block footer_js %}{% endblock %}
    <script>
        $('li.dropdown').mouseover(function() {
            $(this).addClass('open');
        }).mouseout(function() {
            $(this).removeClass('open');
        });

        function change_pass() {
            $('#changepass_modal').modal('show');
        };

        function submit_changepass() {
            var oldpass = $("#oldpass").val();
            var newpass1 = $("#newpass1").val();
            var newpass2 = $("#newpass2").val();
            if (newpass1 != newpass2) {
                bootbox.alert({
                    size: "small",
                    title: "错误",
                    message: "两次密码输入不相同,请检查"
                })
                return
            }
            if (oldpass.length*newpass1.length*newpass2.length===0){
                bootbox.alert({
                    size: "small",
                    title: "错误",
                    message: "填写项不可为空"
                })
                return
            }
            var data = JSON.stringify({"oldpass":oldpass, "newpass":newpass1});
            $.ajax({
                url: "{% url 'changepass' %}",
                type: 'POST',
                dataType: "json",
                data: data,
                async: true,
                success: function(msg) {
                    if (msg["status"]===false){
                        bootbox.alert({
                            size:"small",
                            title: "修改密码失败",
                            message: msg["msg"]
                        });
                    }
                    else{
                        bootbox.alert({
                            size:"small",
                            title: "修改密码成功",
                            message: "修改密码成功,点击确定刷新页面",
                            callback: function(){ 
                                window.location.reload();
                            }
                        })
                    }

                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    bootbox.alert({
                        size:"small",
                        title: "修改密码失败",
                        message: msg["msg"]
                    })
                }
            });
        };
    </script>
</body>

</html>

templates/dashboard.html
{% extends "base.html" %}
{% block title %}Dss导航页{% endblock %}
{% block content_header %}
<h1>
  站点导航
  <small>django sso server</small>
</h1>
<ol class="breadcrumb">
  <li><a href="/"><i class="fa fa-dashboard"></i> 主页</a></li>
  <li><a href="/dashboard/">用户页面</a></li>
  <li class="active">站点导航</li>
</ol>
{% endblock %}
{% block header_css %}
    <style type="text/css">
    .list{
     margin-top:10px;
    }
    </style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if not systems %}
                    <h5><strong>还没有添加任何站点</strong></h5>
                    {% endif %}
                    {% for sys in systems %}
                    <div class="col-md-3 list">
                        <a href="{{ sys.url }}" class="btn btn-info btn-block btn-lg">{{ sys.name }}</a>
                    </div>
                    {% endfor %}
                </div>
                <div class="panel-footer">
                    需要添加站点列表请联系管理员。
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Dss登录{% endblock %}
{% block content_header %}
{% endblock %}
{% block header_css %}
    <style type="text/css">
    #code{
     margin-right:100px;
    }
    </style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="row clearfix">
                <div class="col-md-6 column">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="text-center panel-title">
                                LDAP 登录
                            </h3>
                        </div>
                        <div class="panel-body">
                            <form role="form">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">用户名</label>
                                    <input class="form-control" id="ldap_username" type="text" />
                                    <p class="help-block">
                                        请输入您的ldap账号
                                    </p>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">密码</label>
                                    <input class="form-control" id="ldap_password" type="password" />
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-xs-8">
                                            <label for="exampleInputEmail1">验证码</label>
                                            <input class="form-control" type="text" id="captcha" />
                                            <p class="help-block">
                                                不区分大小写
                                            </p>
                                        </div>
                                        <div class="col-xs-4">
                                            <img id="captcha_img" src="{% url 'api:get_captcha' %}" onclick="refresh_captcha()" style="margin-top: 28px;">
                                            <p class="help-block" onclick="refresh_captcha()">
                                                看不清楚?换一张!
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="panel-footer text-center">
                            <button type="button" class="btn btn-info btn-block" id="login_submit" onclick="ldap_login()">登录</button>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 column">
                    <div class="col-md-offset-2" id="weixin">
                    Panel content
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer_js %}
<script src="http://rescdn.qqmail.com/node/ww/wwopenmng/js/sso/wwLogin-1.0.0.js"></script>
<script>
    //刷新验证码
    function refresh_captcha() {
        $("#captcha_img").attr("src",$("#captcha_img")[0].src + '?');
    };

    function ldap_login(){
        var ldap_username = $("#ldap_username").val();
        var password = $("#ldap_password").val();
        var captcha = $("#captcha").val();
        if (ldap_username.length*password.length*captcha.length===0){
            bootbox.alert({
                size: "small",
                title: "错误",
                message: "填写项不可为空!"
            });
            return            
        };
        var data = JSON.stringify({"ldap_username":ldap_username, "password":password, "captcha":captcha});
        $.ajax({
            url: "{% url 'login' %}",
            type: 'POST',
            dataType: "json",
            data: data,
            async: true,
            success: function(msg) {
                if (msg["status"]===false){
                    bootbox.alert({
                        size: "small",
                        title: "登录失败",
                        message: msg["msg"],
                        callback: function(){
                            window.location.reload();
                        }
                    });
                    return
                };
                if ("{{ redirect_url }}"){
                    window.location.href = "{{ redirect_url }}"
                    return  
                };
                window.location.href = "{% url 'dashboard' %}"
            },
            error: function(XMLHttpRequest, textStatus, errorThrown) {
                bootbox.alert({
                    size: "small",
                    title: "登录失败",
                    message: msg["msg"],
                    callback: function(){
                        window.location.reload();
                    }
                });
            }
        });
    };

    $(document).keypress(function(e) {  
        if(e.which == 13) {
            if (!$(".bootbox").hasClass("in")){
                jQuery("#login_submit").click(); 
            };
        }  
    });  

    //微信登录
    window.WwLogin({
        "id" : "weixin",  
        "appid" : "{{appid}}",
        "agentid" : "{{agentid}}",
        "redirect_uri" :encodeURIComponent("{{redirect_uri}}"),
        "state" : "{{state}}",
    });
</script>

{% endblock %}

templates/startup.html
{% extends "base.html" %}
{% block title %}Dss系统初始化{% endblock %}
{% block content_header %}
    <h1>
      系统初始化
      <small>sso server setup</small>
    </h1>
{% endblock %}

{% block content %}
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">配置初始化信息</h3><i class="fa fa-fw fa-question-circle" title="初始化帮助"  
            data-container="body" data-toggle="popover" data-placement="top" 
            data-content="请填写<认证ldap地址>,<ldap基础dn>,<管理员账号>,<密码>,<sso系统管理员账号>(注意格式,用逗号分隔),<cookie有效期>(单位小时,可不填,默认10小时),<单点登录子域名>(如.calmkart.com)"></i>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form class="form-horizontal">
        <div class="box-body">
            <div class="form-group">
                <div class="col-sm-2"></div>
                <label for="inputEmail3" class="col-sm-2 control-label">ldap host</label>
                <div class="col-sm-4">
                    <input class="form-control" id="host" placeholder="ldap://ldap.calmkart.com:389" type="text">
                </div>
                <div class="col-sm-4"></div>
            </div>
            <div class="form-group">
                <div class="col-sm-2"></div>
                <label for="inputEmail3" class="col-sm-2 control-label">ldap base dn</label>
                <div class="col-sm-4">
                    <input class="form-control" id="basedn" placeholder="ou=people,dc=calmkart,dc=com" type="text">
                </div>
                <div class="col-sm-4"></div>
            </div>
            <div class="form-group">
                <div class="col-sm-2"></div>
                <label for="inputEmail3" class="col-sm-2 control-label">ldap admin</label>
                <div class="col-sm-4">
                    <input class="form-control" id="admin" placeholder="cn=admin,dc=calmkart,dc=com" type="text">
                </div>
                <div class="col-sm-4"></div>
            </div>
            <div class="form-group">
                <div class="col-sm-2"></div>
                <label for="inputEmail3" class="col-sm-2 control-label">ldap pass</label>
                <div class="col-sm-4">
                    <input class="form-control" id="password" placeholder="password!@#" type="text">
                </div>
                <div class="col-sm-4"></div>
            </div>
            <div class="form-group">
                <div class="col-sm-2"></div>
                <label for="inputEmail3" class="col-sm-2 control-label">系统管理员账号</label>
                <div class="col-sm-4">
                    <input class="form-control" id="sys_admin" placeholder="pengng,calmkart,admin" type="text">
                </div>
                <div class="col-sm-4"></div>
            </div>
            <div class="form-group">
                <div class="col-sm-2"></div>
                <label for="inputEmail3" class="col-sm-2 control-label">cookie有效期(选填,单位小时,默认10小时)</label>
                <div class="col-sm-4">
                    <input class="form-control" id="timeout" placeholder="10" type="number">
                </div>
                <div class="col-sm-4"></div>
            </div>
            <div class="form-group">
                <div class="col-sm-2"></div>
                <label for="inputEmail3" class="col-sm-2 control-label">单点登录子域名(选填)</label>
                <div class="col-sm-4">
                    <input class="form-control" id="domain" placeholder=".calmkart.com" type="text">
                </div>
                <div class="col-sm-4"></div>
            </div>
        </div>
    </form>
        <!-- /.box-body -->
        <div class="box-footer">
            <button type="submit" class="btn btn-info pull-right" onclick="setup_submit()">开始初始化系统</button>
        </div>
        <!-- /.box-footer -->
</div>
{% endblock %}

{% block footer_js %}
<script>
    $(function () { 
        $("[data-toggle='popover']").popover();
    });

    function setup_submit(){
        var ldap_url = $("#host").val();
        var basedn = $("#basedn").val();
        var admin = $("#admin").val();
        var password = $("#password").val();
        var sys_admin = $("#sys_admin").val();
        var timeout = $("#timeout").val();
        var domain = $("#domain").val();
        var data = JSON.stringify({
            "ldap_url":ldap_url, 
            "basedn":basedn, 
            "admin":admin, 
            "password":password, 
            "sys_admin":sys_admin,
            "timeout":timeout,
            "domain":domain,
        });
        $.ajax({
            url: "{% url 'start' %}",
            type: 'POST',
            dataType: "json",
            data: data,
            async: true,
            success: function(msg) {
                if (msg["status"]===false){
                    bootbox.alert({
                        title: "初始化失败",
                        message: msg["msg"]
                    });
                }
                else{
                    bootbox.alert({
                        title: "初始化成功",
                        message: "系统初始化成功,点击确认跳转至登录界面",
                        callback: function(){ 
                            window.location.href = "/login/";
                        }
                    })
                }
                
            },
            error: function(XMLHttpRequest, textStatus, errorThrown) {
                bootbox.alert({
                    title: "初始化失败",
                    message: msg["msg"]
                })
            }
        });
    };
</script>

{% endblock %}